title: Gladwin Yeo
email: 
description: >- 
  Thoughts and Ramblings
url: "https://gladwinyjh.github.io"
github_username:  gladwinyjh

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

#Order of header pages
header_pages:
  - projects.markdown
  - writings.markdown
  - about.markdown
  
# Google Analytics so I know no one reads my blog
google_analytics: G-4QRFJBS40F
